
### Get all contacts (local)
GET http://localhost:3000/contacts

### Get single contact by id (local)
GET http://localhost:3000/contacts/6a9cb4ccd85fecf182d4c14d

### Get all contacts (Render)
GET https://contacts-api-v0ht.onrender.com/contacts

### Get single contact (Render)
GET https://contacts-api-v0ht.onrender.com/contacts/6a9cb4ccd85fecf182d4c14d